apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebservice
spec:
  selector:
    matchLabels:
      app: simplewebservice
  replicas: 3
  template:
    metadata:
      labels:
        app: simplewebservice
    spec:
      containers:
        - name: backend
          image: christofbuckxpxl/kubernetes_backend
          ports:
            - containerPort: 8080
  
        - name: frontend
          image: christofbuckxpxl/kubernetes_frontend
          ports:
            - containerPort: 8081
